services:
  web_server:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - user_name=Estudiante
      - write_result=not_show
    networks:
      - user_net 


  postgres:
    container_name: postgres_db 
    image: postgres:latest 
    restart: unless-stopped
    environment: 
      POSTGRES_DB: queue_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - user_net
  
volumes:
  users-data:
  postgres_data:

networks:
  user_net:   
