version: "3.8"

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - user_name=Estudiante
      - write_result=not_show
    networks:
      - user_net 

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - user_net  

volumes:
  postgres-data:

networks:
  users_net:    
